# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          
          # Basic config
          user: anxlz
          template: classic
          base: header, activity, community, repositories, metadata
          base_hireable: yes
          config_display: large
          config_timezone: Africa/Cairo
          config_twemoji: yes
          
          # Core plugins (no auth needed)
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          
          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_threshold: 0%
          plugin_languages_colors: github
          plugin_languages_sections: most-used
          plugin_languages_categories: markup, programming
          plugin_languages_aliases: TS, JS, CSS, HTML, TSX
          
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_habits_languages_limit: 8
          plugin_habits_languages_threshold: 0%
          
          plugin_lines: yes
          plugin_lines_history_limit: 1
          plugin_lines_repositories_limit: 4
          plugin_lines_sections: base
          
          plugin_topics: yes
          plugin_topics_limit: 15
          plugin_topics_mode: starred
          plugin_topics_sort: stars
          
          plugin_stars: yes
          plugin_stars_limit: 4
          
          plugin_introduction: yes
          plugin_introduction_title: yes
          
          plugin_calendar: yes
          plugin_calendar_limit: 1
          
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          
          plugin_activity: yes
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_activity_limit: 5
          plugin_activity_timestamps: yes
          
          plugin_code: yes
          plugin_code_days: 3
          plugin_code_lines: 12
          plugin_code_load: 400
          plugin_code_visibility: public
          
          plugin_followup: yes
          plugin_followup_sections: repositories
          plugin_followup_archived: yes
          
          plugin_reactions: yes
          plugin_reactions_display: absolute
          plugin_reactions_limit: 200
          plugin_reactions_days: 14
          
          plugin_people: yes
          plugin_people_limit: 24
          plugin_people_size: 28
          plugin_people_types: followers, following
          
          plugin_repositories: yes
          plugin_repositories_featured: anxlz/QuizApp
          plugin_repositories_order: featured, pinned, starred, random
          plugin_repositories_pinned: 1
          
          plugin_gists: yes
          
          plugin_notable: yes
          plugin_notable_from: organization
          plugin_notable_repositories: yes
          plugin_notable_types: commit
          
          plugin_discussions: yes
          plugin_discussions_categories: yes
          
          plugin_stargazers: yes
          plugin_stargazers_charts: yes
          plugin_stargazers_charts_type: chartist
          plugin_stargazers_days: 14
          
          plugin_starlists: yes
          plugin_starlists_limit: 2
          plugin_starlists_languages: yes
          plugin_starlists_limit_repositories: 2
          
          # Optional: Add these if you have the credentials
          # plugin_leetcode: yes
          # plugin_leetcode_user: anxlz
          # plugin_leetcode_sections: solved
          
          # plugin_anilist: yes
          # plugin_anilist_user: anxlz
          # plugin_anilist_medias: anime, manga
          # plugin_anilist_sections: favorites
          
          # plugin_chess: yes
          # plugin_chess_user: AnxiL
          # plugin_chess_platform: lichess.org
          
          repositories_forks: yes
